channels:
- conda-forge
- bioconda
- defaults
dependencies:
- arviz=0.11.4
- ca-certificates=2024.8.30
- certifi=2024.8.30
- click=8.1.7
- ipykernel=6.4.2
- jupyterthemes=0.20.0
- loguru=0.7.0
- matplotlib=3.4.3
- mygene=3.2.2
- openpyxl=3.0.9
- openssl=3.3.2
- pandas=1.3.4
- pyro-ppl=1.7.0
- python=3.9.13
- scikit-learn=1.2.2
- seaborn=0.12.0
- xgboost=1.7.4
